class Config:
    NUM_PRODUCERS = 5
    NUM_CONSUMERS = 5
    QUEUE_MAX_SIZE = 10
    PRODUCER_INTERVAL = 0.1
    CONSUMER_INTERVAL = 0.15
    PROGRAM_DURATION = 10
    MIN_NUMBER = 1
    MAX_NUMBER = 100